// Offline assembly tests. No database connection or records.
const assert = require('node:assert/strict')
const { assembleAssessment, DEFAULT_ASSESSMENT_LENGTH } = require('../dist/services/assessmentAssembly')
const { ASSESSMENT_DOMAINS } = require('../dist/models/AssessmentItem')
const items = ASSESSMENT_DOMAINS.flatMap((primaryDomain, d) => Array.from({ length: 10 }, (_, i) => ({
  _id: `${d}-${i}`, itemId: `TEST-${d}-${String(i).padStart(2, '0')}`, primaryDomain,
  isActive: true, responseKey: { private: true }, profileTags: ['low_resource'],
})))
const original = JSON.stringify(items)
const selected = assembleAssessment(items)
assert.equal(selected.length, DEFAULT_ASSESSMENT_LENGTH)
assert.equal(new Set(selected.map(x => x._id)).size, 30)
assert.deepEqual(assembleAssessment([...items].reverse()), selected)
assert.equal(JSON.stringify(items), original)
for (const x of selected) assert(items.includes(x), 'Preserve candidate metadata without mutation')
const counts = ASSESSMENT_DOMAINS.map(d => selected.filter(x => x.primaryDomain === d).length)
assert(Math.max(...counts) - Math.min(...counts) <= 1)
assert.equal(assembleAssessment(items, 7).length, 7)
assert.equal(assembleAssessment(items, 100).length, 90)
assert.deepEqual(assembleAssessment([]), [])
for (const count of [0, -1, 0.5, Infinity, NaN, '30']) assert.throws(() => assembleAssessment(items, count), RangeError)
const sparse = items.filter(x => x.primaryDomain === ASSESSMENT_DOMAINS[0] || x._id === '1-0')
assert.equal(assembleAssessment(sparse, 10).length, 10)
assert(assembleAssessment(sparse, 10).some(x => x._id === '1-0'))
assert.deepEqual(assembleAssessment([...items, ...items]), selected)
assert.deepEqual(assembleAssessment([...items, { ...items[0], _id: 'duplicate-bank-id' }]), selected)
assert.deepEqual(assembleAssessment([{ ...items[0], isActive: false }]), [])
assert.deepEqual(assembleAssessment([{ ...items[0], primaryDomain: 'unknown' }]), [])
assert.deepEqual(assembleAssessment(items.map(x => ({ ...x, profileTags: ['urban'] }))).map(x => x._id), selected.map(x => x._id))
console.log('PASS: deterministic order, all nine domains, balanced/sparse coverage, active-only selection, uniqueness, configurable length, metadata preservation and profile-independent routing.')
